# Generated by Django 4.1.6 on 2023-02-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackingapp', '0002_alter_activity_met'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='carbohydates',
            new_name='carbohydrates',
        ),
    ]
